# This config is used when running tests.
# It is the same for all Aqueduct apps, no need to change
database:
  username: dart
  password: dart
  host: localhost
  port: 5432
  databaseName: dart_test

mqtt:
  username: dart
  password: dart
  host: localhost

scheduler:
  proofsRetrieveSchedule: '*/20 * * * *' # Once every 20 minutes

email:
  host: smtp.eu.sparkpostmail.com
  username: SMTP_Injection
  password: somekey  # Insert key here

chainpoint:
  publicUriUrl:

# prod.validi.city etc
host: localhost