name: validicityserver
description: The server component of Validicity that keeps track of everything.
version: 0.3.0
author: Göran Krampe <goran.krampe@gmail.com>
publish_to: none

environment:
  sdk: ">=2.8.3"

dependencies:
  aqueduct: ^3.3.0+1
  safe_config: ^2.0.2
  mqtt_client: ^7.2.1
  pubspec: ^0.1.4
  intl: ^0.16.1
  timezone: ^0.5.6
  cron: ^0.2.2
  process_run: ^0.10.10+2
  mailer: ^3.0.4
  mime: ^0.9.6+3
  get_it: ^4.0.0

  validicitylib:
    path: ../validicitylib
    #git:
    #  url: git@github.com:Validicity/validicitylib.git

dependency_overrides:
  postgres: 2.1.1

dev_dependencies:
  test: ^1.6.3
  aqueduct_test: ^1.0.1
